#!/usr/bin/env python3
"""
Report Generator Module
Generates security reports in various formats
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any


class ReportGenerator:
    """Generate security scan reports"""
    
    def __init__(self):
        self.timestamp = datetime.now().isoformat()
    
    def save_json(self, results: Dict[str, Any], output_path: str):
        """Save results as JSON"""
        report = {
            "scan_info": {
                "tool": "SecProbe",
                "version": "2.0.0",
                "timestamp": self.timestamp,
                "generated_by": "SecProbe Report Generator"
            },
            "results": results
        }
        
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2, default=str)
    
    def generate_html(self, results: Dict[str, Any]) -> str:
        """Generate HTML report"""
        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SecProbe Security Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               line-height: 1.6; color: #333; background: #f5f5f5; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; 
                     border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
                   gap: 15px; margin: 20px 0; }
        .card { background: #f8f9fa; padding: 20px; border-radius: 8px; 
                border-left: 4px solid #3498db; }
        .card.critical { border-left-color: #e74c3c; }
        .card.high { border-left-color: #e67e22; }
        .card.medium { border-left-color: #f39c12; }
        .card.low { border-left-color: #3498db; }
        .card h3 { margin: 0; font-size: 14px; color: #7f8c8d; text-transform: uppercase; }
        .card .value { font-size: 32px; font-weight: bold; color: #2c3e50; margin-top: 5px; }
        .vulnerability { background: #fff3cd; border: 1px solid #ffeaa7; 
                         border-radius: 6px; padding: 15px; margin: 10px 0; }
        .vulnerability.critical { background: #f8d7da; border-color: #f5c6cb; }
        .vulnerability.high { background: #fff3cd; border-color: #ffeaa7; }
        .vulnerability.medium { background: #d1ecf1; border-color: #bee5eb; }
        .vulnerability.low { background: #d4edda; border-color: #c3e6cb; }
        .severity { display: inline-block; padding: 4px 12px; border-radius: 4px; 
                    font-weight: bold; font-size: 12px; text-transform: uppercase; }
        .severity.critical { background: #dc3545; color: white; }
        .severity.high { background: #fd7e14; color: white; }
        .severity.medium { background: #ffc107; color: black; }
        .severity.low { background: #17a2b8; color: white; }
        pre { background: #f4f4f4; padding: 15px; border-radius: 4px; 
              overflow-x: auto; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #34495e; color: white; }
        tr:hover { background: #f5f5f5; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; 
                  text-align: center; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔒 SecProbe Security Report</h1>
        <p>Generated: {timestamp}</p>
        
        {content}
        
        <div class="footer">
            <p>Generated by SecProbe v1.0.0</p>
            <p>For authorized security testing only</p>
        </div>
    </div>
</body>
</html>"""
        
        content = self._generate_html_content(results)
        return html.format(timestamp=self.timestamp, content=content)
    
    def _generate_html_content(self, results: Dict[str, Any]) -> str:
        """Generate HTML content from results"""
        html_parts = []
        
        # Summary section
        total_vulns = 0
        severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        
        for module, data in results.items():
            if isinstance(data, dict) and "vulnerabilities" in data:
                for vuln in data["vulnerabilities"]:
                    total_vulns += 1
                    severity = vuln.get("severity", "LOW")
                    severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        html_parts.append("<h2>Executive Summary</h2>")
        html_parts.append('<div class="summary">')
        
        for sev, count in severity_counts.items():
            sev_lower = sev.lower()
            html_parts.append(f'''
                <div class="card {sev_lower}">
                    <h3>{sev} Risk</h3>
                    <div class="value">{count}</div>
                </div>
            ''')
        
        html_parts.append('</div>')
        
        # Vulnerabilities section
        html_parts.append("<h2>Vulnerabilities</h2>")
        
        if total_vulns == 0:
            html_parts.append("<p>No vulnerabilities found.</p>")
        else:
            for module, data in results.items():
                if isinstance(data, dict) and "vulnerabilities" in data:
                    for vuln in data["vulnerabilities"]:
                        severity = vuln.get("severity", "LOW").lower()
                        html_parts.append(f'''
                            <div class="vulnerability {severity}">
                                <span class="severity {severity}">{vuln.get("severity")}</span>
                                <h3>{vuln.get("type", "Unknown")}</h3>
                                <p><strong>Description:</strong> {vuln.get("description", "N/A")}</p>
                                <p><strong>Recommendation:</strong> {vuln.get("recommendation", "N/A")}</p>
                                {f'<p><strong>Evidence:</strong> {vuln.get("evidence")}</p>' if vuln.get("evidence") else ""}
                            </div>
                        ''')
        
        # Technical details
        html_parts.append("<h2>Technical Findings</h2>")
        html_parts.append("<pre>" + json.dumps(results, indent=2, default=str) + "</pre>")
        
        return "\n".join(html_parts)
    
    def generate_markdown(self, results: Dict[str, Any]) -> str:
        """Generate Markdown report"""
        lines = [
            "# SecProbe Security Report",
            "",
            f"**Generated:** {self.timestamp}",
            "**Tool:** SecProbe v1.0.0",
            "",
            "---",
            "",
            "## Executive Summary",
            ""
        ]
        
        # Count vulnerabilities
        total_vulns = 0
        severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        
        for module, data in results.items():
            if isinstance(data, dict) and "vulnerabilities" in data:
                for vuln in data["vulnerabilities"]:
                    total_vulns += 1
                    severity = vuln.get("severity", "LOW")
                    severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        lines.append(f"- **Total Vulnerabilities:** {total_vulns}")
        lines.append(f"- **Critical:** {severity_counts['CRITICAL']}")
        lines.append(f"- **High:** {severity_counts['HIGH']}")
        lines.append(f"- **Medium:** {severity_counts['MEDIUM']}")
        lines.append(f"- **Low:** {severity_counts['LOW']}")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Vulnerabilities")
        lines.append("")
        
        if total_vulns == 0:
            lines.append("No vulnerabilities found.")
        else:
            for module, data in results.items():
                if isinstance(data, dict) and "vulnerabilities" in data:
                    for vuln in data["vulnerabilities"]:
                        lines.append(f"### {vuln.get('type', 'Unknown')} ({vuln.get('severity', 'LOW')})")
                        lines.append("")
                        lines.append(f"**Description:** {vuln.get('description', 'N/A')}")
                        lines.append("")
                        lines.append(f"**Recommendation:** {vuln.get('recommendation', 'N/A')}")
                        if vuln.get("evidence"):
                            lines.append("")
                            lines.append(f"**Evidence:** {vuln['evidence']}")
                        lines.append("")
        
        lines.append("---")
        lines.append("")
        lines.append("## Technical Details")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(results, indent=2, default=str))
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by SecProbe v1.0.0*")
        
        return "\n".join(lines)